"""create_questionnaire_tokens

Revision ID: 5255937ce591
Revises: 409adbb221b5
Create Date: 2026-07-13 16:14:01.732509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5255937ce591'
down_revision: Union[str, Sequence[str], None] = '409adbb221b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('passage_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['passage_id'], ['survey_passages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'passage_id', name='uq_contact_passage_token')
    )
    op.create_index(op.f('ix_questionnaire_tokens_id'), 'questionnaire_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_questionnaire_tokens_token'), 'questionnaire_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questionnaire_tokens_token'), table_name='questionnaire_tokens')
    op.drop_index(op.f('ix_questionnaire_tokens_id'), table_name='questionnaire_tokens')
    op.drop_table('questionnaire_tokens')
    # ### end Alembic commands ###
