"""add_two_factor_enabled_to_users

Revision ID: 6946d6a3c80d
Revises: 5aac3d7c9bf2
Create Date: 2026-06-24 01:13:16.571721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6946d6a3c80d'
down_revision: Union[str, Sequence[str], None] = '5aac3d7c9bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_enabled')
    # ### end Alembic commands ###
