"""Add AppNotification model

Revision ID: 7c2a621ca1a3
Revises: e01f6ca381c9
Create Date: 2026-07-12 18:30:37.726128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c2a621ca1a3'
down_revision: Union[str, Sequence[str], None] = 'e01f6ca381c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_notifications_id'), 'app_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_app_notifications_user_id'), 'app_notifications', ['user_id'], unique=False)
    op.alter_column('activities', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('audit_logs', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('sectors', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('surveys', 'periodicity',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ANNUAL', 'MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'BIENNIAL', 'CUSTOM', name='survey_periodicity_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surveys', 'periodicity',
               existing_type=sa.Enum('ANNUAL', 'MONTHLY', 'QUARTERLY', 'SEMI_ANNUAL', 'BIENNIAL', 'CUSTOM', name='survey_periodicity_enum'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('sectors', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('audit_logs', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('activities', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_app_notifications_user_id'), table_name='app_notifications')
    op.drop_index(op.f('ix_app_notifications_id'), table_name='app_notifications')
    op.drop_table('app_notifications')
    # ### end Alembic commands ###
