"""Add action_url to app_notifications

Revision ID: ee5ffabb9b99
Revises: 7c2a621ca1a3
Create Date: 2026-07-12 18:56:48.514381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5ffabb9b99'
down_revision: Union[str, Sequence[str], None] = '7c2a621ca1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_notifications', sa.Column('action_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_notifications', 'action_url')
    # ### end Alembic commands ###
